import React, { useState, useRef, useEffect } from 'react';
import { GoogleGenerativeAI } from '@google/generative-ai';

const systemPrompt = `You are the Uronexa Clinical Copilot, an advanced AI specializing in personalized urinalysis and nephrology.
Your job is to be an interactive, empathetic, and highly dynamic health assistant. Do NOT sound like a rigid robot repeating a template.

CRITICAL INSTRUCTIONS:
1. Be Conversational: Answer the user's specific question naturally and conversationally. Do not dump a giant block of analysis unless they specifically ask for "a full breakdown" or "what is my risk score in detail".
2. Context Aware: You have access to their exact Risk Score and Biomarkers. Use them fluidly to answer their specific question. For example, if they ask "why is my score high?", look at the worst biomarkers and explain *only* those in a friendly way.
3. Be Direct & Helpful: If they just say "hi", greet them warmly, acknowledge their scan is complete, and ask what specific biomarker they are worried about.
4. Vary Your Responses: Every response should sound unique. Use different formatting (paragraphs, short bullet points) depending on the context of the question.
5. Actionable Advice: When giving dietary or health advice, make it highly specific to the biomarker they asked about, but keep it concise and encouraging. Always remind them to see a doctor if their score is high.`;

const ClinicalCopilot = ({ riskScore, biomarkers }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [chatHistory, setChatHistory] = useState([
        {
            role: 'assistant',
            content: "Hello. I am the Uronexa Clinical Copilot. How can I help you understand your urinalysis results today?"
        }
    ]);
    const [inputValue, setInputValue] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const chatEndRef = useRef(null);

    // Auto-scroll to bottom of chat
    useEffect(() => {
        chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [chatHistory]);

    const handleSendMessage = async () => {
        if (!inputValue.trim()) return;

        const userMessage = inputValue;
        setInputValue('');

        // Add user message to UI
        setChatHistory(prev => [...prev, { role: 'user', content: userMessage }]);
        setIsLoading(true);

        try {
            // Prioritize Vite env variable, fallback to generic process.env if needed
            const apiKey = import.meta.env?.VITE_GEMINI_API_KEY || (typeof process !== 'undefined' ? process.env?.VITE_GEMINI_API_KEY : null);

            if (!apiKey) {
                throw new Error("Gemini API key is missing. Please check your environment variables (.env file).");
            }

            const genAI = new GoogleGenerativeAI(apiKey);
            const model = genAI.getGenerativeModel({
                model: 'gemini-flash-latest',
                systemInstruction: systemPrompt
            });

            // Prepare context injected prompt silently
            const contextAwarePrompt = `Patient's Current Data: Risk Score ${riskScore || 'N/A'}, Biomarkers: ${JSON.stringify(biomarkers || {})}. Patient asks: ${userMessage}`;

            // Format history for Gemini SDK
            // Skip the first greeting message as it wasn't generated by the model
            const formattedHistory = chatHistory.slice(1).map(msg => ({
                role: msg.role === 'assistant' ? 'model' : 'user',
                parts: [{ text: msg.content }]
            }));

            const chat = model.startChat({
                history: formattedHistory,
            });

            const result = await chat.sendMessage(contextAwarePrompt);
            const response = await result.response;
            const responseText = response.text();

            setChatHistory(prev => [...prev, { role: 'assistant', content: responseText }]);
        } catch (error) {
            console.error("Copilot Error:", error);
            setChatHistory(prev => [...prev, { role: 'assistant', content: "I'm sorry, I encountered an error connecting to the clinical neural network. Please check your API key configuration or try again later." }]);
        } finally {
            setIsLoading(false);
        }
    };

    const handleKeyDown = (e) => {
        if (e.key === 'Enter') {
            handleSendMessage();
        }
    };

    // Simple Markdown Renderer for bolding and line breaks
    const renderMarkdown = (text) => {
        // Escape HTML to prevent XSS before replacing
        const escapeHtml = (unsafe) => {
            return unsafe
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        };

        let formattedText = escapeHtml(text)
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold
            .replace(/\*(.*?)\*/g, '<em>$1</em>') // Italic
            .replace(/\n/g, '<br />'); // Newlines

        return <div dangerouslySetInnerHTML={{ __html: formattedText }} />;
    };

    return (
        <>
            {/* FLOATING CHAT BUTTON */}
            <button
                onClick={() => setIsOpen(!isOpen)}
                className={`fixed bottom-6 right-6 z-50 p-4 rounded-full shadow-2xl transition-all duration-300 flex items-center justify-center group
                    ${isOpen ? 'bg-red-500 hover:bg-red-600 rotate-90' : 'bg-[#00F0FF] hover:bg-[#00c8ff] hover:scale-110'} 
                `}
                style={{
                    boxShadow: isOpen ? '0 0 20px rgba(239, 68, 68, 0.4)' : '0 0 25px rgba(0, 240, 255, 0.5)'
                }}
            >
                {isOpen ? (
                    <svg className="w-7 h-7 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                ) : (
                    <svg className="w-7 h-7 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                    </svg>
                )}
            </button>

            {/* CHAT MODAL */}
            <div className={`fixed bottom-24 right-6 z-40 w-[400px] h-[550px] max-h-[80vh] flex flex-col rounded-2xl border border-white/20 bg-[#050B14]/95 backdrop-blur-xl shadow-2xl overflow-hidden transition-all duration-300 origin-bottom-right
                ${isOpen ? 'scale-100 opacity-100' : 'scale-0 opacity-0 pointer-events-none'}
            `}>
                {/* Header */}
                <div className="flex items-center gap-3 px-6 py-4 border-b border-white/10 bg-white/5 backdrop-blur-md">
                    <div className="relative flex h-3 w-3">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00F0FF] opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-3 w-3 bg-[#00F0FF]"></span>
                    </div>
                    <h3 className="text-white font-semibold tracking-wide flex-1">Clinical Copilot AI</h3>
                    <span className="text-xs text-[#00F0FF] font-mono bg-[#00F0FF]/10 px-2 py-1 rounded-full border border-[#00F0FF]/20">Secure Connection</span>
                </div>

                {/* Chat Area */}
                <div className="flex-1 overflow-y-auto p-6 space-y-4 bg-white/5 backdrop-blur-sm custom-scrollbar">
                    {chatHistory.map((msg, index) => (
                        <div key={index} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                            <div
                                className={`max-w-[80%] p-4 rounded-2xl ${msg.role === 'user'
                                    ? 'bg-white/10 text-white rounded-br-sm'
                                    : 'bg-white/10 border border-[#00F0FF]/50 text-gray-200 rounded-bl-sm shadow-[0_0_15px_rgba(0,240,255,0.15)]'
                                    }`}
                            >
                                {msg.role === 'user' ? (
                                    <p className="text-sm leading-relaxed">{msg.content}</p>
                                ) : (
                                    <div className="text-sm leading-relaxed space-y-2">
                                        {renderMarkdown(msg.content)}
                                    </div>
                                )}
                            </div>
                        </div>
                    ))}

                    {isLoading && (
                        <div className="flex justify-start">
                            <div className="bg-white/10 border border-[#00F0FF]/30 p-4 rounded-2xl rounded-bl-sm inline-flex items-center gap-2">
                                <span className="w-2 h-2 bg-[#00F0FF] rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></span>
                                <span className="w-2 h-2 bg-[#00F0FF] rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></span>
                                <span className="w-2 h-2 bg-[#00F0FF] rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></span>
                            </div>
                        </div>
                    )}
                    <div ref={chatEndRef} />
                </div>

                {/* Input Area */}
                <div className="p-4 border-t border-white/10 bg-white/5 backdrop-blur-md flex gap-3">
                    <input
                        type="text"
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        onKeyDown={handleKeyDown}
                        placeholder="Ask about your biomarkers or risk score..."
                        className="flex-1 bg-black/40 border border-white/10 text-white placeholder-gray-400 text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-[#00F0FF]/50 transition-colors"
                        disabled={isLoading}
                    />
                    <button
                        onClick={handleSendMessage}
                        disabled={isLoading || !inputValue.trim()}
                        className="bg-[#00FFA3] hover:bg-[#00e08f] text-black font-semibold px-6 py-3 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_0_15px_rgba(0,255,163,0.3)] hover:shadow-[0_0_25px_rgba(0,255,163,0.5)] flex items-center justify-center"
                    >
                        {isLoading ? (
                            <svg className="animate-spin h-5 w-5 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                        ) : (
                            <span>Send</span>
                        )}
                    </button>
                </div>
            </div>
        </>
    );
};

export default ClinicalCopilot;
